export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    GET_RESTAURANTS_REQUEST: "GET_RESTAURANTS_REQUEST",
    GET_RESTAURANTS_SUCCESS: "GET_RESTAURANTS_SUCCESS",
    GET_RESTAURANTS_FAILURE: "GET_RESTAURANTS_FAILURE",


    CREATE_RESTAURANT_REQUEST: "CREATE_RESTAURANT_REQUEST",
    CREATE_RESTAURANT_SUCCESS: "CREATE_RESTAURANT_SUCCESS",
    CREATE_RESTAURANT_FAILURE: "CREATE_RESTAURANT_FAILURE",

    UPDATE_RESTAURANT_REQUEST: "UPDATE_RESTAURANT_REQUEST",
    UPDATE_RESTAURANT_SUCCESS: "UPDATE_RESTAURANT_SUCCESS",
    UPDATE_RESTAURANT_FAILURE: "UPDATE_RESTAURANT_FAILURE",

    DELETE_RESTAURANT_REQUEST: "DELETE_RESTAURANT_REQUEST",
    DELETE_RESTAURANT_SUCCESS: "DELETE_RESTAURANT_SUCCESS",
    DELETE_RESTAURANT_FAILURE: "DELETE_RESTAURANT_FAILURE",

    COMMENT_REQUEST: ' COMMENT_REQUEST',
    COMMENT_REQUEST_SUCCESS: ' COMMENT_REQUEST_SUCCESS',
    COMMENT_REQUEST_FAILURE: 'COMMENT_REQUEST_FAILURE',

    GET_REVIEW_REQUEST: 'GET_REVIEW_REQUEST',
    GET_REVIEW_SUCCESS: 'GET_REVIEW_SUCCESS',
    GET_REVIEW_FAILURE: 'GET_REVIEW_FAILURE',

    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_REQUEST_SUCCESS: 'SIGN_OUT_REQUEST_SUCCESS',
    SIGN_OUT_REQUEST_FAILURE: 'SIGN_OUT_REQUEST_FAILURE'

}